# Generated by Django 2.2.16 on 2021-05-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('applicant_name', models.CharField(max_length=30, verbose_name='申請人姓名')),
                ('applicant_eSchool', models.CharField(max_length=20, verbose_name='申請人負責小學')),
                ('leave_reason', models.CharField(max_length=100, verbose_name='請假原因')),
                ('leave_type', models.CharField(max_length=50, verbose_name='申請假別')),
                ('leave_date', models.DateField(verbose_name='請假日期')),
                ('sub_name', models.CharField(max_length=30, verbose_name='代課姓名')),
                ('sub_eSchool', models.CharField(max_length=20, verbose_name='代課負責小學')),
                ('apply_dateTime', models.DateTimeField(auto_now_add=True, verbose_name='申請提交時間')),
            ],
            options={
                'verbose_name': '請假申請表',
                'verbose_name_plural': '請假申請表',
                'managed': True,
            },
        ),
    ]
