# Generated by Django 2.2.16 on 2021-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_application',
            name='applicant_eSchool',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='sub_eSchool',
        ),
        migrations.AddField(
            model_name='leave_application',
            name='applicant_kidSchool',
            field=models.CharField(default='school', max_length=20, verbose_name='申請人負責學校'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sub_kidSchool',
            field=models.CharField(default='school', max_length=20, verbose_name='代課負責學校'),
            preserve_default=False,
        ),
    ]
