# Generated by Django 2.2.5 on 2019-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('semester', models.CharField(max_length=10, verbose_name='學期')),
                ('score_beginning_education', models.FloatField(verbose_name='期初教育訓練')),
                ('score_attendence', models.FloatField(verbose_name='出席率')),
                ('score_other_activity', models.FloatField(verbose_name='其他活動')),
                ('score_together', models.FloatField(verbose_name='相見歡')),
                ('score_teaching', models.FloatField(verbose_name='教學')),
                ('score_material', models.FloatField(verbose_name='教材')),
                ('score_log', models.FloatField(verbose_name='教學記錄')),
                ('score_late', models.FloatField(verbose_name='遲到')),
                ('score_other', models.FloatField(verbose_name='其他')),
                ('score_total', models.FloatField(verbose_name='總和')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('companion', models.ForeignKey(on_delete='CASCADE', to='user.Companion', verbose_name='大學伴編號')),
            ],
            options={
                'verbose_name': '評量分數',
                'verbose_name_plural': '評量分數',
                'managed': True,
            },
        ),
    ]
