# Generated by Django 2.2.6 on 2020-03-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Companion', verbose_name='大學伴編號'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_late',
            field=models.FloatField(default=0, verbose_name='遲到'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_other',
            field=models.FloatField(default=0, verbose_name='其他'),
        ),
    ]
