# Generated by Django 2.2.16 on 2021-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='stuID',
            field=models.CharField(max_length=100, verbose_name='大學伴學號'),
        ),
    ]
