# Generated by Django 2.2.16 on 2021-06-01 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210601_0232'),
        ('classroom', '0002_auto_20210531_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairing_table',
            old_name='uniCompanion',
            new_name='companion',
        ),
        migrations.RenameField(
            model_name='substitute',
            old_name='sub_uniCompanion',
            new_name='sub_companion',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='stuID',
        ),
        migrations.RemoveField(
            model_name='pairing_table',
            name='kid_name',
        ),
        migrations.RemoveField(
            model_name='pairing_table',
            name='kid_school',
        ),
        migrations.RemoveField(
            model_name='pairing_table',
            name='timeSet_code',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='school',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='timeSet_code',
        ),
        migrations.AddField(
            model_name='meet',
            name='companion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Companion', verbose_name='大學伴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairing_table',
            name='partner_school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Partner_school', verbose_name='夥伴學校'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairing_table',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='小學伴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairing_table',
            name='timeGroup',
            field=models.PositiveIntegerField(default=None, verbose_name='時間組別'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='partner_school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Partner_school', verbose_name='夥伴學校'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='timeGroup',
            field=models.PositiveIntegerField(default=None, verbose_name='時間組別'),
            preserve_default=False,
        ),
    ]
