# Generated by Django 2.2.16 on 2021-06-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210601_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'managed': True, 'verbose_name': '夥伴學校課程表', 'verbose_name_plural': '夥伴學校課程表'},
        ),
    ]
