# Generated by Django 2.2.16 on 2021-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210601_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitute',
            name='pairing_table',
        ),
        migrations.AddField(
            model_name='substitute',
            name='pairing_table_id',
            field=models.PositiveIntegerField(default=None, verbose_name='代課配對'),
            preserve_default=False,
        ),
    ]
