# Generated by Django 2.2.16 on 2021-06-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20210601_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitute',
            name='pairing_table_id',
        ),
        migrations.AddField(
            model_name='substitute',
            name='pairing_table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroom.Pairing_table', verbose_name='配對表'),
            preserve_default=False,
        ),
    ]
