# Generated by Django 2.2.16 on 2021-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20210601_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='meet_code',
            field=models.CharField(default='None', max_length=100, verbose_name='會議代碼'),
        ),
    ]
