# Generated by Django 2.1.7 on 2019-02-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('name', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('starting_time', models.DateTimeField(verbose_name='開始時間')),
                ('ending_time', models.DateTimeField(verbose_name='結束時間')),
                ('location', models.CharField(max_length=100, verbose_name='地點')),
                ('description', models.TextField(blank=True, default='', verbose_name='活動簡介')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Activity_attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('Activity_id', models.PositiveIntegerField()),
                ('User_id', models.PositiveIntegerField()),
                ('checkin_time', models.DateTimeField(verbose_name='簽到時間')),
            ],
            options={
                'verbose_name': '課程出席紀錄',
                'verbose_name_plural': '課程出席紀錄',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('day', models.PositiveIntegerField()),
                ('date', models.DateField(verbose_name='日期')),
                ('starting_time', models.TimeField(verbose_name='開始時間')),
                ('ending_time', models.TimeField(verbose_name='結束時間')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class_attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('Class_id', models.PositiveIntegerField()),
                ('Companion_id', models.PositiveIntegerField()),
                ('checkin_time', models.DateTimeField(verbose_name='簽到時間')),
            ],
            options={
                'verbose_name': '課程出席紀錄',
                'verbose_name_plural': '課程出席紀錄',
                'managed': True,
            },
        ),
    ]
