# Generated by Django 2.1.7 on 2019-02-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True, 'verbose_name': '活動', 'verbose_name_plural': '活動'},
        ),
        migrations.AlterModelOptions(
            name='activity_attendance',
            options={'managed': True, 'verbose_name': '活動出席紀錄', 'verbose_name_plural': '活動出席紀錄'},
        ),
    ]
