# Generated by Django 2.1.7 on 2019-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20190223_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_attendance',
            name='ischecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class_attendance',
            name='ischecked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity_attendance',
            name='checkin_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='簽到時間'),
        ),
        migrations.AlterField(
            model_name='class_attendance',
            name='checkin_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='簽到時間'),
        ),
    ]
