# Generated by Django 2.1.7 on 2019-03-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20190316_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='starting_time',
        ),
    ]
