# Generated by Django 2.2.6 on 2020-03-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_auto_20190316_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_general_attandance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('department_id', models.PositiveIntegerField(verbose_name='系所')),
                ('grade', models.PositiveIntegerField(verbose_name='年級')),
                ('student_ID_number', models.CharField(max_length=100, verbose_name='學號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('Activity_id', models.PositiveIntegerField(verbose_name='活動編號')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='報名時間')),
                ('isCheckedin', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='簽到時間')),
            ],
            options={
                'verbose_name': '一般活動出席紀錄',
                'verbose_name_plural': '一般活動出席紀錄',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True, 'verbose_name': '大學伴活動', 'verbose_name_plural': '大學伴活動'},
        ),
        migrations.AlterModelOptions(
            name='activity_attendance',
            options={'managed': True, 'verbose_name': '大學伴活動出席紀錄', 'verbose_name_plural': '大學伴活動出席紀錄'},
        ),
    ]
