# Generated by Django 2.2.6 on 2020-03-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20200301_0226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity_general_attandance',
            new_name='General_activity_attandance',
        ),
    ]
