# Generated by Django 2.2.6 on 2020-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_auto_20200301_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='isGeneral',
            field=models.BooleanField(default=False, verbose_name='活動類型'),
        ),
    ]
