# Generated by Django 2.2.6 on 2020-03-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_activity_isgeneral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='General_activity_attandance',
            new_name='General_activity_attendance',
        ),
    ]
