# Generated by Django 2.2.6 on 2020-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_auto_20200301_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_activity_attendance',
            name='checkin_time',
            field=models.DateTimeField(null=True, verbose_name='簽到時間'),
        ),
    ]
