# Generated by Django 2.2 on 2021-10-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20210601_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRevision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('semester', models.CharField(max_length=10, verbose_name='學期')),
                ('score_beginning_education', models.FloatField(verbose_name='教育訓練')),
                ('score_attendence', models.FloatField(verbose_name='出席率')),
                ('score_meeting_attendence', models.FloatField(verbose_name='例會出席')),
                ('score_together', models.FloatField(verbose_name='相見歡')),
                ('score_teaching1', models.FloatField(verbose_name='教學表現1')),
                ('score_teaching2', models.FloatField(verbose_name='教學表現2')),
                ('score_material', models.FloatField(verbose_name='自製教材')),
                ('score_log', models.FloatField(verbose_name='教學記錄')),
                ('score_late', models.FloatField(default=0, verbose_name='遲到')),
                ('score_bonus1', models.FloatField(default=0, verbose_name='加值分1')),
                ('score_bonus2', models.FloatField(default=0, verbose_name='加值分2')),
                ('score_total', models.FloatField(verbose_name='總和')),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Companion', verbose_name='大學伴編號')),
            ],
            options={
                'verbose_name': '評量分數',
                'verbose_name_plural': '評量分數',
                'managed': True,
            },
        ),
    ]
