# Generated by Django 2.2.16 on 2021-06-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='note',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.AddField(
            model_name='student',
            name='isJoin',
            field=models.BooleanField(default=True, verbose_name='是否參加計畫'),
        ),
    ]
