# Generated by Django 2.2.16 on 2021-06-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210601_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='User_id',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
