# Generated by Django 2.1.7 on 2019-02-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('Category_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='New_app', max_length=300)),
                ('display_name', models.CharField(default='New_app', max_length=300)),
                ('icon', models.CharField(default='subject', max_length=100)),
                ('isDropdown', models.BooleanField(default=True)),
                ('isPublic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '應用程式',
                'verbose_name_plural': '應用程式',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='App_dropdown_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('App_id', models.PositiveIntegerField()),
                ('title', models.CharField(default='New_item', max_length=300)),
                ('icon', models.CharField(default='subject', max_length=100)),
                ('link', models.CharField(default='#', max_length=300, verbose_name='URL')),
            ],
            options={
                'verbose_name': '應用程式子項目',
                'verbose_name_plural': '應用程式子項目',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('title', models.CharField(default='New_category', max_length=300)),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('App_id', models.PositiveIntegerField()),
                ('User_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '應用程式權限',
                'verbose_name_plural': '應用程式權限',
                'managed': True,
            },
        ),
    ]
